linters:
  default: none
  enable:
    - loglint

	linters-settings:
	  custom:
	    loglint:
	      path: ./loglint.so
	      description: Linter for checking log messages
	      original-url: github.com/loglint/loglint
