run:
  timeout: 5m

linters:
  enable-all: true
  disable:
    - tenv
    - godox
    - gochecknoglobals
    - nlreturn
    - testpackage

linters-settings:
  depguard:
    rules:
      allow_analysis:
        list-mode: lax
        files:
          - "pkg/analyzer/**"
          - "plugin/**"
        allow:
          - "golang.org/x/tools/go/analysis"
          - "golang.org/x/tools/go/analysis/passes/inspect"

  tagliatelle:
    case:
      use-field-name: false
      rules:
        json: snake
        yaml: snake
